name: nitori_core
description: Core Module for Nitori.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

# Note: remove this line when we want to publish this package.
publish_to: none

environment:
  sdk: ^3.1.4

# Add regular dependencies here.
dependencies:
  json_annotation: '4.8.1'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.3.3
  json_serializable: '6.7.1'
