name: nitori_message
description: Message Builder for Nitori.
version: 0.0.1
repository: https://github.com/kawashiro-juukou/nitori/tree/master/pkgs/nitori_message
issue_tracker: https://github.com/kawashiro-juukou/nitori/issues

environment:
  sdk: ^3.1.4

dependencies: {}

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
