name: nitori_server
description: Dart Server Implementation for Satori Protocol.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.4

# Add regular dependencies here.
dependencies:
  nitori_core:
    path: ../nitori_core

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
