# Created with package:mono_repo v6.6.0
name: Dart CI
on:
  push:
    branches:
      - main
      - master
  pull_request:
  schedule:
    - cron: "0 0 * * 0"
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github
permissions: read-all

jobs:
  job_001:
    name: mono_repo self validate
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@d6a63dab3335f427404425de0fbfed4686d93c4f
        with:
          sdk: stable
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - name: mono_repo self validate
        run: dart pub global activate mono_repo 6.6.0
      - name: mono_repo self validate
        run: dart pub global run mono_repo generate --validate
  job_002:
    name: "analyze_and_format; linux; Dart 3.1.4; `dart analyze --fatal-infos .`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:3.1.4;packages:pkgs/nitori;commands:analyze"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:3.1.4;packages:pkgs/nitori
            os:ubuntu-latest;pub-cache-hosted;sdk:3.1.4
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@d6a63dab3335f427404425de0fbfed4686d93c4f
        with:
          sdk: "3.1.4"
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - id: pkgs_nitori_pub_upgrade
        name: pkgs/nitori; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: pkgs/nitori
      - name: "pkgs/nitori; dart analyze --fatal-infos ."
        run: dart analyze --fatal-infos .
        if: "always() && steps.pkgs_nitori_pub_upgrade.conclusion == 'success'"
        working-directory: pkgs/nitori
  job_003:
    name: "analyze_and_format; linux; Dart dev; `dart analyze --fatal-infos .`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:pkgs/nitori;commands:analyze"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:pkgs/nitori
            os:ubuntu-latest;pub-cache-hosted;sdk:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@d6a63dab3335f427404425de0fbfed4686d93c4f
        with:
          sdk: dev
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - id: pkgs_nitori_pub_upgrade
        name: pkgs/nitori; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: pkgs/nitori
      - name: "pkgs/nitori; dart analyze --fatal-infos ."
        run: dart analyze --fatal-infos .
        if: "always() && steps.pkgs_nitori_pub_upgrade.conclusion == 'success'"
        working-directory: pkgs/nitori
  job_004:
    name: "analyze_and_format; linux; Dart dev; `dart format --output=none --set-exit-if-changed .`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:pkgs/nitori;commands:format"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:pkgs/nitori
            os:ubuntu-latest;pub-cache-hosted;sdk:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@d6a63dab3335f427404425de0fbfed4686d93c4f
        with:
          sdk: dev
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - id: pkgs_nitori_pub_upgrade
        name: pkgs/nitori; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: pkgs/nitori
      - name: "pkgs/nitori; dart format --output=none --set-exit-if-changed ."
        run: "dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.pkgs_nitori_pub_upgrade.conclusion == 'success'"
        working-directory: pkgs/nitori
  job_005:
    name: "unit_test; linux; Dart 3.1.4; `dart test --test-randomize-ordering-seed=random`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:3.1.4;packages:pkgs/nitori;commands:test"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:3.1.4;packages:pkgs/nitori
            os:ubuntu-latest;pub-cache-hosted;sdk:3.1.4
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@d6a63dab3335f427404425de0fbfed4686d93c4f
        with:
          sdk: "3.1.4"
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - id: pkgs_nitori_pub_upgrade
        name: pkgs/nitori; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: pkgs/nitori
      - name: "pkgs/nitori; dart test --test-randomize-ordering-seed=random"
        run: "dart test --test-randomize-ordering-seed=random"
        if: "always() && steps.pkgs_nitori_pub_upgrade.conclusion == 'success'"
        working-directory: pkgs/nitori
    needs:
      - job_001
      - job_002
      - job_003
      - job_004
  job_006:
    name: "unit_test; linux; Dart dev; `dart test --test-randomize-ordering-seed=random`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:pkgs/nitori;commands:test"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:pkgs/nitori
            os:ubuntu-latest;pub-cache-hosted;sdk:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@d6a63dab3335f427404425de0fbfed4686d93c4f
        with:
          sdk: dev
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - id: pkgs_nitori_pub_upgrade
        name: pkgs/nitori; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: pkgs/nitori
      - name: "pkgs/nitori; dart test --test-randomize-ordering-seed=random"
        run: "dart test --test-randomize-ordering-seed=random"
        if: "always() && steps.pkgs_nitori_pub_upgrade.conclusion == 'success'"
        working-directory: pkgs/nitori
    needs:
      - job_001
      - job_002
      - job_003
      - job_004
  job_007:
    name: "unit_test; windows; Dart 3.1.4; `dart test --test-randomize-ordering-seed=random`"
    runs-on: windows-latest
    steps:
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@d6a63dab3335f427404425de0fbfed4686d93c4f
        with:
          sdk: "3.1.4"
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - id: pkgs_nitori_pub_upgrade
        name: pkgs/nitori; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: pkgs/nitori
      - name: "pkgs/nitori; dart test --test-randomize-ordering-seed=random"
        run: "dart test --test-randomize-ordering-seed=random"
        if: "always() && steps.pkgs_nitori_pub_upgrade.conclusion == 'success'"
        working-directory: pkgs/nitori
    needs:
      - job_001
      - job_002
      - job_003
      - job_004
  job_008:
    name: "unit_test; windows; Dart dev; `dart test --test-randomize-ordering-seed=random`"
    runs-on: windows-latest
    steps:
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@d6a63dab3335f427404425de0fbfed4686d93c4f
        with:
          sdk: dev
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - id: pkgs_nitori_pub_upgrade
        name: pkgs/nitori; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: pkgs/nitori
      - name: "pkgs/nitori; dart test --test-randomize-ordering-seed=random"
        run: "dart test --test-randomize-ordering-seed=random"
        if: "always() && steps.pkgs_nitori_pub_upgrade.conclusion == 'success'"
        working-directory: pkgs/nitori
    needs:
      - job_001
      - job_002
      - job_003
      - job_004
