name: Health

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

permissions:
  contents: read
  pull-requests: write

jobs:
  health:
    uses: dart-lang/ecosystem/.github/workflows/health.yaml@main
